### ISSUE TITLE
Namespaced rdf attributes in xhtml?

### ISSUE THREAD

**Issue by skript-cc** [rubensworks/rdfa-streaming-parser.js#27]
Is it possible to namespace rdf attributes in xhtml?

If I understand everything correctly, the snippet below should be valid RDFa in xhtml. When I feed this into the parser, the articleBody does not get parsed as an html datatype. It does, when I remove the rdf: namespace.

In the project I'm working on, I need the rdf: namespace, because another library serializes data* attributes as kebab case. (I also filed an issue there).

Your code doesn't seem to do any kind of normalization on attribute names (neither does htmlparser2). I wonder if support for this use case is missing, or if I misunderstand something about (rdf) namespaces.

```html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns">
<head><title>Test namespace</title></head>
<body vocab="http://schema.org/">
<article typeof="Article">
  <p property="articleBody" rdf:datatype="rdf:HTML">
    <strong>Rich</strong>
    <em>Text</em>
  </p>
</article>
</body
</html>
```

**Comment by rubensworks** [comment]
I'm afraid that this is not possible according to [the RDFa spec](https://www.w3.org/TR/rdfa-core/#h-note6):

> the attributes in this specification SHOULD be defined in 'no namespace' (e.g., when the attributes are used on elements in the Host Language's namespace, they can be used with no qualifying prefix: <myml:myElement property="license">). 

By adding the `rdf:` prefix, the attribute is different, and will not apply to RDFa anymore.

You will get the same result when using other RDFa parsers.

**Comment by skript-cc** [comment]
Thanks for clearing that up! I'm no expert in RDF(a), and all the specs are a bit overwhelming.
